#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Perfo\Commands\ConcurrentlyCommand;
use Perfo\Commands\OneByOneCommand;
use Symfony\Component\Console\Application;

$application = new Application('Perfo', '0.1');

// ... register commands
$application->add(new OneByOneCommand);
$application->add(new ConcurrentlyCommand);

$application->run();
